### ISSUE TITLE
Can't get it to work for dotnet project

### ISSUE THREAD

**Issue by mawett** [microsoft/azure-pipelines-artifact-caching-tasks#13]
I'm trying to cache the NuGet packages that we need for our asp.net core project, so far without success.
I have the following definition:
```
steps:
- task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreAndSaveCacheV1.RestoreAndSaveCache@1
  inputs:
    keyfile: '**/*.csproj, **/*.sln'
    targetfolder: '$(backendFolder)packages/'
    vstsFeed: '$(ArtifactFeed)'
- script: dotnet restore 'Backend.sln' --packages 'packages/'
  condition: ne(variables['CacheRestored'], 'true')
  displayName: 'dotnet restore'
  workingDirectory: '$(backendFolder)'
- script: dotnet build 'Backend.sln' --configuration $(buildConfiguration) --no-restore
  workingDirectory: '$(backendFolder)'
  displayName: 'dotnet build $(buildConfiguration)'
```

I tried various combinations, but so far none seems to work. I guess I am making a basic mistake, but can't figure it out, so any help is appreciated!
What I noticed in the build output:
```
{"@t":"2019-04-28T14:49:13.2701438Z","@m":"Can't find the package 'xy-ci' with version '1.0.0-linux-83d1e3cdf979d3a31a12e7fd49ef4f8dc76ee52086ef493622cf3c747d712369' in feed 'ArtifactCache'.","@i":"23b82bea","@l":"Error","SourceContext":"ArtifactTool.Program","UtcTimestamp":"2019-04-28 14:49:13.270Z"}
Cache miss:  linux-83d1e3cdf979d3a31a12e7fd49ef4f8dc76ee52086ef493622cf3c747d712369

```
When I check the feed, the package is not there. But how does the caching step come to that number if it does not exist?

**Comment by jessehouwing** [comment]
The nuget packages are restored to the `%userprofile%\.nuget\packages` folder. To cache them you need to redirect that folder by setting the `NUGET_PACKAGES` variable on your agent or in your build  definition.

`NUGET_PACKAGES = $(Build.SourcesDirectory)\.nuget\packages`

That will put the packages in a location the task can cache them for you.

**Comment by jessehouwing** [comment]
Note that this will cause the build to start with an empty cache. You can further speed up the build by moving the original .nuget folder from the %appdata% folder.

**Comment by mawett** [comment]
Thanks for this hint. I added the variable as shown, but I'm not sure if it works correctly. Does it matter where you add it (as a pipeline variable through the DevOps interface or directly in the YAML file?)
I ended up with the following description in the YAML file now:
```
steps:
- task: RestoreAndSaveCache@1
  inputs:
    keyfile: '**/*.sln'
    targetfolder: '$(NUGET_PACKAGES)'
    feedList: '$(ArtifactFeed)'
- script: dotnet restore 'Backend.sln'
  workingDirectory: '$(backendFolder)'
  condition: ne(variables['CacheRestored'], 'true')
  displayName: 'dotnet restore'
- script: dotnet build 'Backend.sln' --configuration $(buildConfiguration)
  workingDirectory: '$(backendFolder)'
  displayName: 'dotnet build $(buildConfiguration)'
```
It now has a cache hit in the RestoreAndSave and dotnet restore is skipped because CacheRestore is set.
However, dotnet build then still restores the packages since it can't seem to find them. I additionally added the parameter '--source $(NUGET_PACKAGES)' to dotnet build, which results in the message 'The local source '/home/vsts/work/1/s/.nuget/packages' doesn't exist'.
Additionally, it looks like when setting '**/*.sln, **/*.csproj' the cache isn't hit at all during the RestoreAndSaveCache so I just use *.sln at the moment.

Sorry, I'm quite new to this, so it I'm probably making some newbie mistakes along the way, but if you have any additional input, I would greatly appreciate it :)

**Comment by jessehouwing** [comment]
The variable must be set as an Environment Variable prior to calling restore. WHen definign a variable in the UI it should be promoted to an environment variable automatically. You shouldn't need to pass it to the restore task, it should pick up the cache from the environment automatically.

**Comment by mawett** [comment]
After some more testing it looks like the cache (.tar.gz file) is downloaded from the feed, but not unpacked to the $(Build.SourcesDirectory)/.nuget/packages folder.
The variable is stored as an environment variable through the UI.
I tested this by adding two command line tasks after the RestoreAndSaveCache task. One with 'ls /home/vsts/work/1/s/tmp_cache' which shows the *.tar.gz file and another one with 'ls $(Build.SourcesDirectory)/.nuget/packages' which fails, because the directory does not exist. Then the dotnet core build task runs and downloads the NuGets from nuget.org. After that they exist in the defined directory.
Am I misunderstanding something here?

**Comment by erdennis13** [comment]
Hey @mawett, I apologize for my delaying in seeing this. I created a sample dotnet project and build pipeline to show how to get these tasks working with a dotnet project. 

The environment variables are set in yml and referenced in the rest of the build:
```yaml
variables:
  NUGET_PACKAGES: $(Build.SourcesDirectory)/packages
  keyfile: '**/*.csproj, salt.txt'
  vstsFeed: '6fc17501-8e8c-43c5-a4c4-d8559d0b540f'

steps:
- task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
  displayName: 'Restore artifact based on: **/*.csproj, salt.txt'
  inputs:
    keyfile: $(keyfile)
    targetfolder: $(NUGET_PACKAGES)
    vstsFeed: $(vstsFeed)
```

The full yml file can be found [here](https://dev.azure.com/etdenn/PipelineCachingSamples/_git/DotNet.PipelineCachingSample?path=%2Fci%2Fazure-pipelines.yml&version=GBmaster) and a sample build result is [here](https://dev.azure.com/etdenn/PipelineCachingSamples/_build/results?buildId=266).

Let me know if this gets you in the right direction.

**Comment by mawett** [comment]
Hi Ethan

Thanks for taking the time and setting up the sample. I gave it another try, but unfortunately I'm seeing the same behaviour as before. The cache is hit, the cached package is downloaded and the restore step is skipped. However, when building with:
```
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

```

it will restore the packages again. I also added the salt.txt now, but it made no difference. The only difference I saw between your sample is that we build on a hosted Ubuntu Agent, whereas your build uses macOS, but I don't think that this should make the difference.

**Comment by erdennis13** [comment]
Can you try adding the `--no-restore` argument to the build command?
```yaml
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'
  displayName: 'dotnet build $(buildConfiguration)'
```
