### ISSUE TITLE
Save Artifcat step is skipped.

### ISSUE THREAD

**Issue by johngrant** [microsoft/azure-pipelines-artifact-caching-tasks#16]
I have a build pipeline that is running on an Hosted VS2017 build agent. I configured according to the documentation. My save step is always skipped and the log is mostly empty. 

Restore Step Yaml:
```
steps:
- task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
  displayName: 'Restore artifact based on: **/package-lock.json'
  inputs:
    keyfile: '**/package-lock.json'
    targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
    vstsFeed: 'e8aefeda-ecd2-4565-b851-45926c23210b'
```
Save Step Yaml:
```
steps:
- task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
  displayName: 'Save artifact based on: **/package-lock.json'
  inputs:
    keyfile: '**/package-lock.json'
    targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
    vstsFeed: 'e8aefeda-ecd2-4565-b851-45926c23210b'
```
And this is the log from the save step:

2019-04-22T20:55:20.0033358Z ##[section]Starting: Save artifact based on: **/package-lock.json
2019-04-22T20:55:20.0135291Z ==============================================================================
2019-04-22T20:55:20.0135352Z Task         : Save cache
2019-04-22T20:55:20.0135390Z Description  : Saves a cache with Universal Artifacts given a specified key.
2019-04-22T20:55:20.0135439Z Version      : 1.0.10
2019-04-22T20:55:20.0135472Z Author       : Microsoft Corp
2019-04-22T20:55:20.0135503Z Help         : 
2019-04-22T20:55:20.0135551Z ==============================================================================
2019-04-22T20:55:44.1025528Z ##[section]Finishing: Save artifact based on: **/package-lock.json

**Comment by shimms** [comment]
I had the same issue, tried a few different configs, and got it working with this one:

```
- task: SaveCache@1
  inputs:
    keyfile: '$(Build.SourcesDirectory)/Gemfile.lock'
    targetfolder: '$(Build.SourcesDirectory)/vendor/bundle'
    feedList: 'tambo-gems'
```

This is a ruby project, not node, but hopefully this is applicable and you can use it to get yours working.

This is our restore step:

```
- task: RestoreCache@1
  inputs:
    keyfile: '$(Build.SourcesDirectory)/Gemfile.lock'
    targetfolder: '$(Build.SourcesDirectory)/vendor/bundle'
    feedList: 'tambo-gems'
```

**Comment by johngrant** [comment]
Thanks for the reply I updated the save task to the following, but the save step is still skipped:

```
steps:
- task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
  displayName: 'Save artifact based on: **/package-lock.json, $(Build.SourcesDirectory)/package-lock.json'
  inputs:
    keyfile: '**/package-lock.json, $(Build.SourcesDirectory)/package-lock.json'
    targetfolder: '**/node_modules, !**/node_modules/**/node_modules, $(Build.SourcesDirectory)/node_modules'
    vstsFeed: 'e8aefeda-ecd2-4565-b851-45926c23210b'
```

And this is the log output.

```
2019-05-14T18:57:15.4752046Z ##[section]Starting: Save artifact based on: **/package-lock.json, $(Build.SourcesDirectory)/package-lock.json
2019-05-14T18:57:15.4859027Z ==============================================================================
2019-05-14T18:57:15.4859099Z Task         : Save cache
2019-05-14T18:57:15.4859146Z Description  : Saves a cache with Universal Artifacts given a specified key.
2019-05-14T18:57:15.4859225Z Version      : 1.0.10
2019-05-14T18:57:15.4859487Z Author       : Microsoft Corp
2019-05-14T18:57:15.4859523Z Help         : 
2019-05-14T18:57:15.4859796Z ==============================================================================
2019-05-14T18:57:39.6863685Z ##[section]Finishing: Save artifact based on: **/package-lock.json, $(Build.SourcesDirectory)/package-lock.json

```

**Comment by erdennis13** [comment]
Is the source of the build a forked repository? 

If not, it would be super helpful to see the full build logs if you don't mind sending them to me at etdenn at microsoft dot com.

**Comment by erdennis13** [comment]
One other thing to try would be to exclude package-lock.json from the keyfile pattern in the node_modules directory (node packages pull down this when resolved). It's likely not excluding them is causing a cache miss due to the key changing (more files match the pattern after resolving).

For example: 
```yaml
steps:
- task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
  displayName: 'Save artifact based on: **/package-lock.json, $(Build.SourcesDirectory)/package-lock.json'
  inputs:
    keyfile: '**/package-lock.json, !**/node_modules/**/package-lock.json, $(Build.SourcesDirectory)/package-lock.json'
    targetfolder: '**/node_modules, !**/node_modules/**/node_modules, $(Build.SourcesDirectory)/node_modules'
    vstsFeed: 'e8aefeda-ecd2-4565-b851-45926c23210b'
```

**Comment by DerekLiang** [comment]
[7.txt](https://github.com/microsoft/azure-pipelines-artifact-caching-tasks/files/3230142/7.txt)
[5.txt](https://github.com/microsoft/azure-pipelines-artifact-caching-tasks/files/3230143/5.txt)

The following is the configuration as suggested by @erdennis13. 

I think a better implementation should use the exact the same file for hashing or just upload the artifacts without checking the hash.

Thank you in advance for any tips!

```
steps:
- task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreAndSaveCacheV1.RestoreAndSaveCache@1
  displayName: 'Restore and save artifact based on: **/package-lock.json, !**/node_modules/**/package-lock.json, $(Build.SourcesDirectory)/package-lock.json'
  inputs:
    keyfile: '**/package-lock.json, !**/node_modules/**/package-lock.json, $(Build.SourcesDirectory)/package-lock.json'
    targetfolder: '**/node_modules, !**/node_modules/**/node_modules, $(Build.SourcesDirectory)/node_modules'
    vstsFeed: 'df8aea1e-330b-468f-9add-4dedbca53a3f'
```

**Comment by erdennis13** [comment]
@DerekLiang nothing immediately jumps out to me in the logs. Are you installing npm packages via `npm ci` or `npm install`? I'd suggest trying `npm ci` to avoid the `package-lock.json` files from getting modified during the build process.

**Comment by DerekLiang** [comment]
indeed that was the problem. Thank you for the tip.

**Comment by johngrant** [comment]
> [7.txt](https://github.com/microsoft/azure-pipelines-artifact-caching-tasks/files/3230142/7.txt)
> [5.txt](https://github.com/microsoft/azure-pipelines-artifact-caching-tasks/files/3230143/5.txt)
> 
> The following is the configuration as suggested by @erdennis13.
> 
> I think a better implementation should use the exact the same file for hashing or just upload the artifacts without checking the hash.
> 
> Thank you in advance for any tips!
> 
> ```
> steps:
> - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreAndSaveCacheV1.RestoreAndSaveCache@1
>   displayName: 'Restore and save artifact based on: **/package-lock.json, !**/node_modules/**/package-lock.json, $(Build.SourcesDirectory)/package-lock.json'
>   inputs:
>     keyfile: '**/package-lock.json, !**/node_modules/**/package-lock.json, $(Build.SourcesDirectory)/package-lock.json'
>     targetfolder: '**/node_modules, !**/node_modules/**/node_modules, $(Build.SourcesDirectory)/node_modules'
>     vstsFeed: 'df8aea1e-330b-468f-9add-4dedbca53a3f'
> ```

Ignoring node_modules and just using package-lock.json for the cache key fixed my issue also.

**Comment by HybridFox** [comment]
> @DerekLiang nothing immediately jumps out to me in the logs. Are you installing npm packages via `npm ci` or `npm install`? I'd suggest trying `npm ci` to avoid the `package-lock.json` files from getting modified during the build process.

Wouldnt this defeat the point of caching since `npm ci` deletes the `node_modules` that has just been restored from the cache?

**Comment by erdennis13** [comment]
@HybridFox for this to work with `npm ci`, you will need to use "Optimistic cache restoration" and skip `npm ci` if a cache was restored.

E.g.
```yaml
steps:
- task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreAndSaveCacheV1.RestoreAndSaveCache@1
  displayName: 'Restore and save artifact based on: **/package-lock.json, !**/node_modules/**/package-lock.json, $(Build.SourcesDirectory)/package-lock.json'
  inputs:
    keyfile: '**/package-lock.json, !**/node_modules/**/package-lock.json, $(Build.SourcesDirectory)/package-lock.json'
    targetfolder: '**/node_modules, !**/node_modules/**/node_modules, $(Build.SourcesDirectory)/node_modules'
    vstsFeed: 'df8aea1e-330b-468f-9add-4dedbca53a3f'

- script: |
    npm ci
  displayName: Install Dependencies
  condition: ne(variables['CacheRestored'], 'true')
```
