### ISSUE TITLE
How could I cache the Nuget restore task?

### ISSUE THREAD

**Issue by davidop** [Microsoft/azure-pipelines-artifact-caching-tasks#37]
Inside my pipe I have a task that restores the nuget packages, could I improve the performance of this task with its extension?

**Comment by ethanis** [comment]
Hi David! 

Depending on how many packages you are resolving, you may indeed see some perf gains by adding caching. However, I would recommend using the built in [Pipeline Caching](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#netnuget) tasks as they will soon have all the features of this repository's tasks.

With the built in tasks, you could cache resolved nuget packages like so:

```yaml
variables:
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

steps:
...
- task: Cache@2
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/*.csproj'
    restoreKeys: |
       nuget | "$(Agent.OS)"
       nuget
    path: $(NUGET_PACKAGES)
  displayName: Cache NuGet packages
...
```

**Comment by davidop** [comment]
What if I don't use PackageReferences to manage NuGet dependencies? They are classic applications in the .NET Framework

**Comment by ethanis** [comment]
Does that mean you're using `packages.config` files to manage nuget dependencies? 

```yaml
variables:
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

steps:
...
- task: Cache@2
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.config'
    restoreKeys: |
       nuget | "$(Agent.OS)"
       nuget
    path: $(NUGET_PACKAGES)
  displayName: Cache NuGet packages
...
```
